#!/bin/sh

# Set default start/boot
#-----------------------

logger -p local6.notice -t installer "app-dropbox - enabling Dropbox"
chkconfig dropbox on >/dev/null 2>&1

logger -p local6.notice -t installer "app-dropbox - starting Dropbox"
service dropbox start >/dev/null 2>&1
