#!/bin/sh

# Upgrade to 19.4.12 requires restart
#------------------------------------

logger -p local6.notice -t installer "app-dropbox-core - conditional restart after upgrade"

/usr/bin/systemctl daemon-reload

members=`getent group dropbox_plugin | sed 's/.*\://'`
result=$?
if [ "${result}" -eq "0" ] ; then
    IFS=',' read -ra users <<< "$members"
    echo "Restarting Dropbox for $user after upgrade"
    for user in "${users[@]}"; do
        /usr/bin/systemctl restart dropbox@$user.service
    done
fi
