<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['dropbox_account_initialize_busy'] = 'Usługa Dropbox jest zajęta inicjując innego użytkownika.';
$lang['dropbox_app_description'] = 'Usługa hostingu plików Dropbox, zarządzana jest przez firmę Dropbox, Inc., która oferuje przestrzeń dyskową w chmurze, synchronizację plików oraz oprogramowanie klienckie.';
$lang['dropbox_app_name'] = 'Dropbox';
$lang['dropbox_folder_size'] = 'Rozmiar folderu';
$lang['dropbox_missing_home_folder'] = 'Brakuje folderu domowego - sprawdź dostęp użytkownika do usługi plików.';
$lang['dropbox_no_data'] = 'Brak danych...';
$lang['dropbox_reset_complete'] = 'Twój lokalny folder Dropbox został usunięty a informacje o synchronizacji zresetowane.';
$lang['dropbox_reset_confirm'] = 'Zalecane jest usunięcie powiązania tego urządzenia z kontem Dropbox zanim zostanie zresetowany (usunięty) Twój lokalny folder Dropbox.';
$lang['dropbox_reset_delete'] = 'Resetuj/Usuń lokalny folder';
$lang['dropbox_service_not_running'] = 'Usługa Dropbox nie jest uruchomiona.';
$lang['dropbox_starting_service'] = 'You will not be able to start the Dropbox service until at least one user has configured their account.  Login to Webconfig as a user (non-root) and run through the Dropbox syncronization setup.';
$lang['dropbox_status_not_initialized'] = 'Oczekująca inicjacja użytkownika';
$lang['dropbox_user_invalid'] = 'Nazwa użytkownika Dropbox jest nieprawidłowa.';
$lang['dropbox_user_no_access'] = 'Administrator nie umożliwił temu użytkownikowi dostępu do usługi Dropbox.';
$lang['dropbox_users'] = 'Użytkownicy Dropbox';
